### ISSUE TITLE
oofem using Cuda

### ISSUE THREAD

**Issue by xuhenry** [Micket/oofem#5]
Hello,
    Is there anyone who want to accelerate the oofem code based on CUDA?
    And now, CUDA is supported in PETSc. And the CUDA PETSc can be used in OOFEM?
Thanks a lot!
Regard,
Henry

**Comment by Micket** [comment]
Sorry for the delayed reply (we don't usually do these things through github for OOFEM).
Any linear solver available in PETSc should work in OOFEM, simply by using the normal PETSc flags like -mat_type ...
